import { IDropDownItem, IListFormat } from '../core/common.model';

export const POLICY_LIST_TABS: Array<IListFormat> = [
    {
        id: 'cancellation',
        name: 'Cancellation',
    },
    {
        id: 'guarantee',
        name: 'Guarantee',
    },
    {
        id: 'deposit',
        name: 'Deposit',
    }
];

export const SEARCH_EM_SORT_OPTIONS = {
    LAST_MODIFIED_DATE_FIELD_NAME: 'lastModifiedDate',
    DEPOSIT_RULE_NAME: 'depositRuleName',
    LAST_MODIFIED_DATE_DESC_SORT_TYPE: 'D',
    LAST_MODIFIED_DATE_ASC_SORT_TYPE: 'A'
};

export enum SEARCH_SORT_DROPDOWN_OPTIONS {
    SORT_BY_LAST_MODIFIED_DATE = 'SORT_BY_LAST_MODIFIED_DATE',
    SORT_BY_LAST_MODIFIED_DATE_ASCENDING = 'SORT_BY_LAST_MODIFIED_DATE_ASCENDING',
    SORT_BY_LAST_MODIFIED_DATE_DESCENDING = 'SORT_BY_LAST_MODIFIED_DATE_DESCENDING',
    SORT_BY_NAME_A_Z = 'SORT_BY_NAME_A_Z',
    SORT_BY_NAME_Z_A = 'SORT_BY_NAME_Z_A',
    SORT_BY_OLDEST_MODIFIED_DATE = 'SORT_BY_START_DATE' // API is using SORT_BY_START_DATE instead of SORT_BY_OLDEST_MODIFIED_DATE
}

export const SEARCH_PORPERTY_SORT_OPTIONS = {
  DEPOSIT_RULE_NAME: 'Name',
  DESC_SORT_TYPE: 'D',
  ASC_SORT_TYPE: 'A'
};

export const SORT_DROPDOWN: Array<IListFormat> = [
    {
        id: SEARCH_SORT_DROPDOWN_OPTIONS.SORT_BY_LAST_MODIFIED_DATE,
        name: SEARCH_SORT_DROPDOWN_OPTIONS.SORT_BY_LAST_MODIFIED_DATE
    },
    /*,
    {
        id: SEARCH_SORT_DROPDOWN_OPTIONS.SORT_BY_OLDEST_MODIFIED_DATE,
        name: SEARCH_SORT_DROPDOWN_OPTIONS.SORT_BY_OLDEST_MODIFIED_DATE
    },*/
    {
        id: SEARCH_SORT_DROPDOWN_OPTIONS.SORT_BY_NAME_A_Z,
        name: SEARCH_SORT_DROPDOWN_OPTIONS.SORT_BY_NAME_A_Z
    },
    {
        id: SEARCH_SORT_DROPDOWN_OPTIONS.SORT_BY_NAME_Z_A,
        name: SEARCH_SORT_DROPDOWN_OPTIONS.SORT_BY_NAME_Z_A
    }
];

export const SORT_DROPDOWN_ENTERPRISE_POLICIES:  Array<IListFormat> = [
    {
        id: SEARCH_SORT_DROPDOWN_OPTIONS.SORT_BY_LAST_MODIFIED_DATE_DESCENDING,
        name: SEARCH_SORT_DROPDOWN_OPTIONS.SORT_BY_LAST_MODIFIED_DATE_DESCENDING
    },
    {
        id: SEARCH_SORT_DROPDOWN_OPTIONS.SORT_BY_LAST_MODIFIED_DATE_ASCENDING,
        name: SEARCH_SORT_DROPDOWN_OPTIONS.SORT_BY_LAST_MODIFIED_DATE_ASCENDING
    }
];

export const SORT_DROPDOWN_DEPOSIT_CONFIG: Array<IListFormat> = [
    {
        id: SEARCH_EM_SORT_OPTIONS.LAST_MODIFIED_DATE_FIELD_NAME,
        name: SEARCH_SORT_DROPDOWN_OPTIONS.SORT_BY_LAST_MODIFIED_DATE
    },
    {
        id: SEARCH_EM_SORT_OPTIONS.DEPOSIT_RULE_NAME,
        name: SEARCH_SORT_DROPDOWN_OPTIONS.SORT_BY_NAME_A_Z
    },
    {
        id: SEARCH_EM_SORT_OPTIONS.DEPOSIT_RULE_NAME,
        name: SEARCH_SORT_DROPDOWN_OPTIONS.SORT_BY_NAME_Z_A
    }
];

export const SORT_DROPDOWN_PROPERTY_DEPOSIT_CONFIG: Array<IListFormat> = [
  {
      id: SEARCH_PORPERTY_SORT_OPTIONS.DEPOSIT_RULE_NAME,
      name: SEARCH_SORT_DROPDOWN_OPTIONS.SORT_BY_NAME_A_Z
  },
  {
      id: SEARCH_PORPERTY_SORT_OPTIONS.DEPOSIT_RULE_NAME,
      name: SEARCH_SORT_DROPDOWN_OPTIONS.SORT_BY_NAME_Z_A
  }
];
